# -*- coding: utf-8 -*-
"""Copy of Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xpQayiGQ9I4iYj3jrNjzHrrp99R1kNPl
"""

L= ["RAM",1,"SHAYAM",2,"AMAN",3]
print(L)
L1 =[]
L2 = []
for i in L :
    try :
        L1.append(int(i))
    except :
        L2.append(i)
L1.sort()
L2.sort()
L = L1+ L2
print(L)
import sys

print('The command line arguments are:')
for i in sys.argv:
    print(i)

print('\n\nThe PYTHONPATH is', sys.path, '\n')